image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest

pages:
  stage: deploy
  artifacts:
    paths:
      - "*.deb"
    expire_in: 2 day
  script:
    - gitlab-ci-git-buildpackage
    - gitlab-ci-lintian
    - gitlab-ci-autopkgtest
    - gitlab-ci-aptly
